library(tidyverse)
library(here)
library(deSolve)
library(shiny)
library(bslib)
library(bsicons)
## library(shinyhelper)
library(shinyjs)
library(shinyvalidate)
## library(shinyWidgets)
library(rlang)
library(R.utils)
library(readxl)
library(writexl)
library(plotly)
library(DT)
library(reactlog)
## library(waiter)
library(shinyFeedback)

options(shiny.reactlog=TRUE)

## FUNCTIONS
updateNumericInputs <- function(defaults, session) {
  if (any(is.null(dim(defaults)), dim(defaults)[1] != 1)) {
    warning("The `defaults` dataframe is not a single row!")
    print(defaults) # DONT remove this. It's intentional, not for development.
  }
  iwalk(defaults, \(value, inputId) {
    updateNumericInput(session, inputId, value = value)
  })
}

numericInputWithMathJax <-
  function(inputId, rateLabel, initialValue) {
    withMathJax(numericInput(
      inputId,
      sprintf(r"[Rate of %s (\(\%s\))]", rateLabel, inputId),
      value = initialValue,
      min = 0,
      max = 1,
      step = 0.01,
      width = "300px"
    ))
  }

## Add all of the rules generated by rule function factories to a validator;
## do not apply the functions if the list of inputs and rule vectors is empty
## (ruleList) is empty, or if the vector of rules for a single input is empty.
addRuleListToValidator <- function(validator, ruleList) {
  if (length(ruleList)) {
    mapply(
      function(inputId, ruleVector) {
        validator$add_rule(inputId, sv_required())
        if (length(ruleVector)) {
          ## inputId is intentionally recycled ♺!
          mapply(validator$add_rule, inputId, ruleVector)
        }
      },
      names(ruleList),
      ruleList
    )
  }

  validator$enable()
  invisible(validator)
}

here::i_am("global.R")

## DONE: do not modify the column types given below; they are current as of
## 2024-05-23. They should only change if the ordering of columns changes.
columnTypes <- c(
  "text", # Model name
  ## WARN DONT: using logicals in any way, it inexplicably borks everything. A
  ## character vector is used to hold the string "numeric," as modified below.
  character(16)
)
columnTypes[2:17] <- "numeric"
defaultInputValues <- read_xlsx(here("data/defaultInputValues.xlsx"),
                                col_types = columnTypes,
                                sheet = "Ashok")

## defaultColumnTypesWithAdditionalColumns <- c("text", # Model name
##                                              character(16))
## defaultColumnTypesWithAdditionalColumns[2:17] <- "numeric"
## TODO: the type of the additional columns

## TODO: implement the necessary UI and server logic to have the following be
## meaningful to the application.
## publishedInputValues <- read_xlsx(here("data/defaultInputValues.xlsx"),
##                                   col_types = defaultColumnTypesWithAdditionalColumns,
##                                   sheet = "Literature")

## INITIALIZATION
## MAYBE FIXME: do we need an app.R at all? Is global.R a replacement, or is it
## just an additional file? What about a two-file app, with server.R and ui.R?
shinyAppDir(here::here()) # and hurrah!
