library(tidyverse)
library(here)
library(deSolve)
library(shiny)
library(bslib)
library(bsicons)
library(shinyhelper)
library(shinyjs)
library(shinyvalidate)
library(shinyWidgets)
library(shinycssloaders)
library(colourpicker)
library(rlang)
library(R.utils)
library(readxl)
library(writexl)
library(plotly)
library(DT)
library(reactlog)
library(shinyFeedback)
library(reshape2)
source("R/plotter.R")

## Project-local packages
if (!require(ehpi))
  devtools::install_github("bryce-carson/ehpi")
library(ehpi)

options(shiny.reactlog = TRUE)

## FUNCTIONS
updateNumericInputs <- function(defaults, session) {
  if (any(is.null(dim(defaults)), dim(defaults)[1] != 1)) {
    warning("The `defaults` dataframe is not a single row!")
    print(defaults) # DONT remove this. It's intentional, not for development.
  }
  purrr::iwalk(defaults, \(value, inputId) {
    updateNumericInput(session, inputId, value = value)
  })
}

numericInputWithMathJax <-
  function(inputId, rateLabel, initialValue) {
    withMathJax(numericInput(
      inputId,
      sprintf(r"[Rate of %s (\(\%s\))]", rateLabel, inputId),
      value = initialValue,
      min = 0,
      max = 1,
      step = 0.01,
      width = "300px"
    ))
  }

## Add all of the rules generated by rule function factories to a validator; do
## not apply the functions if the list of inputs and rule vectors is empty
## (ruleList has a length of zero), or if the vector of rules for a single input
## has a length of zero.
##
## This has the side effect of enabling the validator.
##
## Returns the validator invisibly.
addRuleListToValidator <- function(validator, ruleList) {
  if (length(ruleList)) {
    mapply(
      function(inputId, ruleVector) {
        validator$add_rule(inputId, sv_required())
        if (length(ruleVector)) {
          ## inputId is intentionally recycled ♺!
          mapply(validator$add_rule, inputId, ruleVector)
        }
      },
      names(ruleList),
      ruleList
    )
  }

  validator$enable()
  invisible(validator)
}

here::i_am("global.R")

defaultInputValues <- read_xls(here("data/defaultInputValues.xls"),
                                col_types = c(rep("text", 3), rep("numeric", 18)),
                                sheet = "Ashok")

## INITIALIZATION
shinyAppDir(here::here()) # and hurrah!
