library(tidyverse)
library(here)
library(deSolve)
library(shiny)
library(bslib)
library(bsicons)
library(shinyhelper)
library(shinyjs)
library(shinyvalidate)
library(shinyWidgets)
library(shinycssloaders)
library(colourpicker)
library(rlang)
library(R.utils)
library(readxl)
library(writexl)
library(plotly)
library(DT)
library(reactlog)
library(shinyFeedback)
library(reshape2)
library(magrittr)
library(reactR)

## HACK NOTE: it is prohibited by box to use library(box), so you must use renv
## to ensure that box is installed on the remote shinyapps.io server. HACK NOTE:
## The box package is requried for using box::use to use reactcharteditor as a
## local module, rather than as a formal, traditional R package installed from
## GitHub.
stopifnot("box" %in% installed.packages())

updateNumericInputs <- function(defaults, session) {
  if (any(is.null(dim(defaults)), dim(defaults)[1] != 1)) {
    warning("The `defaults` dataframe is not a single row!")
    print(defaults) # DONT remove this. It's intentional, not for development.
  }
  purrr::iwalk(defaults, \(value, inputId) {
    updateNumericInput(session, inputId, value = value)
  })
}

numericInputWithMathJax <-
  function(inputId, rateLabel, initialValue) {
    withMathJax(numericInput(
      inputId,
      sprintf(r"[Rate of %s (\(\%s\))]", rateLabel, inputId),
      value = initialValue,
      min = 0,
      max = 1,
      step = 0.01,
      width = "300px"
    ))
  }

## Add all of the rules generated by rule function factories to a validator; do
## not apply the functions if the list of inputs and rule vectors is empty
## (ruleList has a length of zero), or if the vector of rules for a single input
## has a length of zero.
##
## This has the side effect of enabling the validator.
##
## Returns the validator invisibly.
addRuleListToValidator <- function(validator, ruleList) {
  if (length(ruleList)) {
    mapply(
      function(inputId, ruleVector) {
        validator$add_rule(inputId, sv_required())
        if (length(ruleVector)) {
          ## inputId is intentionally recycled ♺!
          mapply(validator$add_rule, inputId, ruleVector)
        }
      },
      names(ruleList),
      ruleList
    )
  }

  validator$enable()
  invisible(validator)
}

here::i_am("global.R")

## reactcharteditor is a "module" in the box sense, and it is a git submodule
## located in the R/ subfolder of the Shiny application, alongside the scripts
## and other R dependencies which are automatically loaded by Shiny. Shiny does
## not automatically load reactcharteditor, however, because it does not recurse
## through subdirectories of R/ for automatically attaching packages.
options(box.path = here("R"))
box::use(reactcharteditor/R/plotly_editor)

defaultInputValues <- read_xls(here("data/defaultInputValues.xls"),
                                col_types = c(rep("text", 3), rep("numeric", 18)),
                                sheet = "Ashok")

shinyAppDir(here::here()) # and hurrah, we initialize the application!
