server <- function(input, output, session) {
  documentReadyPainter() # Restyle some elements with JavaScript.
  disable(selector = "#stochastic > div:nth-child(2) > label:nth-child(2) > input:nth-child(1)")

  # Functions, such as the solveAndRender dispatcher -----------------------------
  updateNumericInputs <- function(defaults, session) {
    if (any(is.null(dim(defaults)), dim(defaults)[1] != 1)) {
      warning("The `defaults` dataframe is not a single row!")
      print(defaults)
    }
    iwalk(defaults, \(value, inputId) {
      updateNumericInput(session, inputId, value = value)
    })
  }

  renderNumericInputWithMathJax <-
    function(inputId, label) {
      numericInputWithMathJax <-
        withMathJax(numericInput(
          inputId,
          label,
          0.5,
          min = 0,
          max = 3,
          step = 0.01,
          width = "300px"
        ))
      ## Evaluate the renderUI function call in the parent environment, so the
      ## expected environment that renderUI runs in is the server function
      ## scope, rather than below another function. numericInputWithMathJax is
      ## substituted, so renderUI it is the already-evaluated result of the
      ## above assignment expresison.
      eval.parent(bquote(renderUI({
        .(numericInputWithMathJax)
      })))
    }

  # Validation --------------------------------------------------------------
  ## Add all of the rules generated by rule function factories to a validator.
  addRuleListToValidator <- function(validator, ruleList) {
    mapply(
      function(inputId, ruleVector) {
        validator$add_rule(inputId, sv_required())
        ## inputId is intentionally recycled while adding the rules in
        ## ruleVector.
        mapply(validator$add_rule, inputId, ruleVector)
      },
      names(ruleList),
      ruleList
    )

    ## Enable the validator and return it invisibly.
    validator$enable()
    invisible(validator)
  }

  ## NOTE: all inputs have the required rule automatically added.
  globalValidator <- addRuleListToValidator(
    InputValidator$new(),
    filter(rules, is.na(model))[, 2][[1]][[1]]
  )

  validatorsAndLambdas <-
    filter(rules, !is.na(model)) |>
    rowwise() |>
    mutate(
      vld = list(addRuleListToValidator(InputValidator$new(), ruleList)),
      ## The body of the lambda may need to be embraced.
      lambda = list(eval(bquote(\() input$modelSelect == .(model))))
    ) |>
    select(vld, lambda)

  ## NOTE: condition each validator upon its corresponding lambda, and then add
  ## each validator to the global validator as a child.
  isolate(
    mapply(
      FUN = \(validator, lambda) {
        validator$condition(lambda)
        ## NOTE: the return value of the previous statement is unused. It's
        ## void!
        globalValidator$add_validator(validator)
      },
      validatorsAndLambdas[[1]],
      validatorsAndLambdas[[2]]
    )
  )

  # Reactives ---------------------------------------------------------------
  defaults <- reactive({
    if (!(input$modelSelect %in% "")) {
      filter(
        defaultInputValues,
        modelType == input$modelSelect,

        ## WARN DONT: using logicals in any way seems to bork everything.
        stochastic == input$stochastic,
        vitalDynamics == input$vitalDynamics,
        massAction == input$trueMassAction
      ) |>
        select(beta:replicates) |>
        select(where(\(x) all(!is.na(x))))
    }
  })

  output$modelDiagram <- renderUI({
    req(input$modelSelect)
    if (!(input$modelSelect %in% "")) {
      tagList(
        img(
          src = paste0("images/", input$modelSelect, ".png"),
          contentType = "image/png",
          height = "40px",
          alt = "The diagram of the model compartments failed to load, or the accessibility text is being read by a screen reader."
        )
      )
    }
  })

  modellingFunctions <-
    reactive({
      mget(
        paste0(
          c("solve", "plot", "plotSubPlots", "plotPhasePlane"),
          input$modelSelect
        ),
        envir = environment(solveSusceptibleInfected),
        mode = "function"
      )
    })

  # Observables -------------------------------------------------------------
  # MODEL SELECT: update numeric inputs to model defaults on change. --------
  ## Whenever the model selection changes (whether the parameters and variables
  ## are set manually or taken from pre-defined models), the widget values
  ## throughout the application are updated as appropriate.
  observeEvent(input$modelSelect, {
    ## If no model is selected, hide the model configuration and action buttons.
    if (input$modelSelect %in% "") {
      hide("actionButtons")
      hide("modelConfiguration")
    } else {
      ## Widget visibility and labelling
      hide("outputPanel")
      ## NOTE: this triggers the anonymous function in
      ## www/whenModelSelectChangesTypesetLaTeX.js to be called, typesetting the
      ## updated labels.
      if (grepl("SI", input$modelSelect, ignore.case = TRUE)) {
        output$beta <- renderNumericInputWithMathJax("beta", r"[Rate of infection (\(\beta\))]")
        output$gamma <- renderNumericInputWithMathJax("gamma", r"[Rate of recovery (\(\gamma\))]")
      } else if (grepl("SEI", input$modelSelect, ignore.case = TRUE)) {
        output$beta <- renderNumericInputWithMathJax("beta", r"[Rate of exposure (\(\beta\))]")
        output$gamma <- renderNumericInputWithMathJax("gamma", r"[Rate of infection (\(\gamma\))]")
      }
      updateNumericInputs(defaults(), session)
      show("modelConfiguration")
      show("actionButtons")
    }
  })

  createSubPlotsUI <- function(subplots) {
    plot_output_list <- lapply(seq_along(subplots), function(i) {
      plotname <- paste("subplot", i, sep = "")
      output[[plotname]] <- plotly::renderPlotly({
        plotly::ggplotly(subplots[[i]])
      })
      column(6, plotly::plotlyOutput(plotname))
    })

    fluidRow(
      lapply(plot_output_list, function(plot_output) {
        plot_output
      })
    )
  }

  # StochasticSelect --------------------------------------------------------
  ## NOTE: hide the output panel and update the input widgets with defaults when
  ## the user changes to stochastic modelling.
  observeEvent(input$stochasticSelect, {
    hide("outputPanel")
    updateNumericInputs(defaults(), session)
  })

  # GO: show outputPanel; call modelling function; render LaTeX. ------------
  ## Toggle the visibility of the outputPanel based on the user's interactions
  ## with the "go" actionButton.
  observeEvent(input$go, {
    show("outputPanel")

    modelSolver <- modellingFunctions()[[1]]
    modelPlotter <- modellingFunctions()[[2]]
    modelSubPlotter <- modellingFunctions()[[3]]
    modelPhasePlanePlotter <- modellingFunctions()[[4]]

    ## NOTE: this reactive value is created by JavaScript. See the corresponding
    ## JavaScript code in modelSelect.js.
    inputs <- isolate(reactiveValuesToList(input))
    inputs <- inputs[ ! inputs %in% input$hiddenInputs]
    eval(substitute({
      modelResults <- doCall.default(
        .fcn = modelSolver,
        args = inputs,
        .ignoreUnusedArguments = TRUE
      )

      output$modelPlot <-
        renderPlotly(ggplotly(modelPlotter(modelResults)))

      output$modelSubPlots <-
        renderUI(createSubPlotsUI(modelSubPlotter(modelResults)))

      output$modelPhasePlane <-
        renderPlotly(ggplotly(modelPhasePlanePlotter(modelResults)))

      output$modelSummaryTable <- renderDT({
        if (!grepl("SE?IRD", input$modelSelect, ignore.case = TRUE)) {
          modelResults <- select(modelResults, !D)
        }
        datatable(
          round(modelResults, 2),
          options = list(
            dom = "lprti",
            pageLength = 50
          ),
          rownames = FALSE
        )
      })

      output$modelLaTeX <- renderUI(renderModelLaTeX(inputs))

      output$downloadData <- downloadHandler(
        filename = function() {
          paste(input$modelSelect, "_Model_Summary", Sys.Date(), ".xlsx", sep = "")
        },
        content = function(file) {
          write_xlsx(modelResults, file)
        }
      )
    }))
  })


  # RESET: hide outputPanel; modelConfiguration; actionButtons; rese --------
  observeEvent(input$resetAll, {
    ## Widget visibility
    hide("outputPanel")
    hide("actionButtons")
    hide("modelConfiguration")

    ## Model options widget values
    updatePickerInput(session, "modelSelect", selected = "")
    updateRadioButtons(session, "trueMassAction", selected = 0)
    updateRadioButtons(session, "stochasticSelect", selected = 0)
    updateCheckboxInput(session, "vitalDynamics", value = FALSE)

    ## Simulation options widget values
    updateNumericInput(session, "timesteps", value = 100)
  })

  ## HACK: wrapping input in a reactive, despite it already being a reactive
  ## value, allows the observable to depend on all inputs simultaneously, and
  ## forces the expression to be recalculated whenever any input is changed,
  ## because the reactive value allInput() will be invalidated and recalculated.
  ## Returning NULL or something else in the reactive wouldn't work; the value
  ## needs to be dependent on all inputs, so invisibly returning all inputs is a
  ## useful hack to quickly solve the issue.
  allInput <- reactive({
    invisible(input)
  })
  observe({
    allInput()
    if (globalValidator$is_valid()) enable("go") else disable("go")
  })
}
