server <- function(input, output, session) {
# Functions, such as the solveAndRender dispatcher -----------------------------
  updateNumericInputs <- function(defaults, session) {
    if (any(is.null(dim(defaults)), dim(defaults)[1] != 1)) {
      warning("The `defaults` dataframe is not a single row!")
      print(defaults)
    }
    iwalk(defaults, \(value, inputId) {
      updateNumericInput(session, inputId, value = value)
    })
  }

  ## Add all of the rules generated by rule function factories to a validator,
  ## and optionally condition those rules on condition.
  addRuleListToValidator <- function(validator, ruleList) {
    mapply(
      function(inputId, ruleVector) {
        ## inputId is intentionally recycled while adding the rules in
        ## ruleVector.
        mapply(validator$add_rule, inputId, ruleVector)
        validator$add_rule(inputId, sv_required())
      },
      names(ruleList),
      ruleList
    )

    ## Enable the validator and return it invisibly.
    validator$enable()
    invisible(validator)
  }


  # Validation --------------------------------------------------------------

  ## NOTE: all inputs have the required rule automatically added.
  globalValidator <- addRuleListToValidator(
    InputValidator$new(),
    filter(rules, is.na(model))[, 2][[1]][[1]]
  )

  model_rules <- filter(rules, !is.na(model))

  lapply(1:nrow(model_rules), function(i) {
    model_name <- model_rules$model[i]
    rule_list <- model_rules$ruleList[[i]]
    assign(
      paste0(model_name, "Validator"),
      addRuleListToValidator(InputValidator$new(), rule_list),
      envir = .GlobalEnv
    )
  })

  # Reactives ---------------------------------------------------------------
  defaults <- reactive({
    if (!(input$modelSelect %in% "")) {
      filter(
        defaultInputValues,
        modelType == input$modelSelect,
        stochastic == input$stochastic,
        vitalStatistics == input$vitalStatistics,
        massAction == input$trueMassAction
      ) |>
        select(beta:replicates) |>
        select(where(\(x) all(!is.na(x))))
    }
  })

  modellingFunctions <-
    reactive({
      mget(
        paste0(
          c("solve", "plot", "plotPhasePlane"),
          input$modelSelect
        ),
        envir = environment(solveSusceptibleInfected),
        mode = "function"
      )
    })

  # Observables -------------------------------------------------------------
  # MODEL SELECT: update numeric inputs to model defaults on change. --------
  ## Whenever the model selection changes (whether the parameters and variables
  ## are set manually or taken from pre-defined models), the widget values
  ## throughout the application are updated as appropriate.
  observeEvent(input$modelSelect, {
    ## If no model is selected, hide the model configuration and action buttons.
    if (input$modelSelect %in% "") {
      hide("actionButtons")
      hide("modelConfiguration")
    } else {
      ## Validation
      ## NOTE: when the selected model is changed the condition for that validator
      ## object (for the selected model) is set to TRUE, and all other
      ## model-specific validators' condition is set to FALSE.
      for (model in c("SIR", "SIRS", "SIRD", "SEIR", "SEIRS", "SEIRD")) {
        modelValidator <- get(paste0(model, "Validator"), envir = .GlobalEnv)
        modelValidator$condition(\() input$modelSelect == model)
        ## NOTE: while this is re-run every time the model is changed, it will
        ## only have an effect a single time, and there will neither be multiple
        ## references to the child validator in the list of children of this
        ## validator (the global one), nor will there be any side-effects.
        # globalValidator$add_validator(modelValidator)
        globalValidator$add_validator(modelValidator)
      }

      ## Widget visibility and labelling
      hide("outputPanel")
      updateNumericInputs(defaults(), session)
      ## NOTE: this triggers the anonymous function in
      ## www/whenModelSelectChangesTypesetLaTeX.js to be called, typesetting the
      ## updated labels.
      if (grepl("SI", input$modelSelect, ignore.case = TRUE)) {
        updateNumericInput(session, "beta", r"[Rate of infection ($ \beta $)]")
        updateNumericInput(session, "gamma", r"[Rate of recovery ($ \gamma $)]")
      } else if (grepl("SEI", input$modelSelect, ignore.case = TRUE)) {
        updateNumericInput(session, "beta", r"[Rate of exposure ($ \beta $)]")
        updateNumericInput(session, "gamma", r"[Rate of infection ($ \gamma $)]")
      }
      show("modelConfiguration")
      show("actionButtons")

      ## FIXME: RStudio's MathJax is broken, and calling it borks reactivity.
      ## runjs(modelSelectJavaScript)
    }
  })

  # StochasticSelect --------------------------------------------------------
  ## NOTE: hide the output panel and update the input widgets with defaults when
  ## the user changes to stochastic modelling.
  observeEvent(input$stochasticSelect, {
    hide("outputPanel")
    updateNumericInputs(defaults(), session)
  })

  # GO: show outputPanel; call modelling function; render LaTeX. ------------
  ## Toggle the visibility of the outputPanel based on the user's interactions
  ## with the "go" actionButton.
  observeEvent(input$go, {
    show("outputPanel")

    modelSolver <- modellingFunctions()[[1]]
    modelPlotter <- modellingFunctions()[[2]]
    modelPhasePlanePlotter <- modellingFunctions()[[3]]

    eval(substitute({
      inputs <- reactiveValuesToList(input)
      modelResults <- doCall.default(
        .fcn = modelSolver,
        args = inputs,
        .ignoreUnusedArguments = TRUE
      )
      output$modelPlot <- renderPlot(modelPlotter(modelResults))
      output$modelPhasePlane <- renderPlot(modelPhasePlanePlotter(modelResults))
      output$modelSummaryTable <- DT::renderDataTable(DT::datatable(modelResults[, 1:6]))
      output$modelLaTeX <- renderUI(renderModelLaTeX(inputs))

      output$downloadData <- downloadHandler(
        filename = function() {
          paste(input$modelSelect, "_Model_Summary", Sys.Date(), ".xlsx", sep = "")
        },
        content = function(file) {
          writexl::write_xlsx(modelResults[, 1:6], file)
        }
      )

      ## FIXME: RStudio's MathJax is broken, and calling it borks reactivity.
      ## runjs(modelSelectJavaScript)
    }))
  })


  # RESET: hide outputPanel; modelConfiguration; actionButtons; rese --------
  ## TODO: resetting the application should set the widget values to those which
  ## are defined for the model in the spreadsheet.
  observeEvent(input$resetAll, {
    ## Widget visibility
    hide("outputPanel")
    hide("actionButtons")
    hide("modelConfiguration")

    ## Model options widget values
    updatePickerInput(session, "modelSelect", selected = "")
    updateRadioButtons(session, "trueMassAction", selected = 0)
    updateRadioButtons(session, "stochasticSelect", selected = 0)
    updateCheckboxInput(session, "vitalStatistics", value = FALSE)

    ## Simulation options widget values
    updateNumericInput(session, "timesteps", value = 100)

    ## FIXME: RStudio's MathJax is broken, and calling it borks reactivity.
    ## runjs(modelSelectJavaScript)
  })

  ## FIXME: the input is not being validated properly, because the global
  ## validator is returning the incorrect value and "go" is never being enabled.
  # observeEvent(input, {
  # if(globalValidator$is_valid()) {
  #      enable("go")
  #    } else {
  #      disable("go")
  #    }
  #  })
}
